// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oabrlvqztszacpksxzxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hYnJsdnF6dHN6YWNwa3N4enh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODEzNzgsImV4cCI6MjA1Nzc1NzM3OH0.-g8h0b7SBkfb_ScxH3etfZr_qr0jojOy7L9eAssyggk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);